-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.challenge_proposals DROP CONSTRAINT IF EXISTS "challenge_proposals_assessorId_fkey";

ALTER TABLE IF EXISTS public.challenge_proposals DROP CONSTRAINT IF EXISTS "challenge_proposals_studentId_award_challenge_fkey";

ALTER TABLE IF EXISTS public.challenge_submission DROP CONSTRAINT IF EXISTS "challenge_submission_assessorId_fkey";

ALTER TABLE IF EXISTS public.challenge_submission DROP CONSTRAINT IF EXISTS "challenge_submission_studentId_award_challenge_fkey";

ALTER TABLE IF EXISTS public.logs DROP CONSTRAINT IF EXISTS "logs_studentId_award_challenge_fkey";

ALTER TABLE IF EXISTS public.student_challenge DROP CONSTRAINT IF EXISTS "student_challenge_approvedProposalId_fkey";

ALTER TABLE IF EXISTS public.student_challenge DROP CONSTRAINT IF EXISTS "student_challenge_approvedSubmissionId_fkey";

ALTER TABLE IF EXISTS public.student_challenge DROP CONSTRAINT IF EXISTS student_challenge_award_fkey;

ALTER TABLE IF EXISTS public.student_challenge DROP CONSTRAINT IF EXISTS student_challenge_challenge_fkey;

ALTER TABLE IF EXISTS public.student_challenge DROP CONSTRAINT IF EXISTS "student_challenge_mentorId_fkey";

ALTER TABLE IF EXISTS public.student_challenge DROP CONSTRAINT IF EXISTS "student_challenge_studentId_fkey";



DROP TABLE IF EXISTS public.assessors;

CREATE TABLE IF NOT EXISTS public.assessors
(
    "assesorId" uuid NOT NULL,
    award text COLLATE pg_catalog."default",
    state location,
    CONSTRAINT assessors_pkey PRIMARY KEY ("assesorId")
);

DROP TABLE IF EXISTS public.awards;

CREATE TABLE IF NOT EXISTS public.awards
(
    award text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT awards_pkey PRIMARY KEY (award)
);

DROP TABLE IF EXISTS public.challenge;

CREATE TABLE IF NOT EXISTS public.challenge
(
    challenge text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT challenge_pkey PRIMARY KEY (challenge)
);

DROP TABLE IF EXISTS public.challenge_proposals;

CREATE TABLE IF NOT EXISTS public.challenge_proposals
(
    "proposalId" uuid NOT NULL,
    "studentId" uuid NOT NULL,
    award text COLLATE pg_catalog."default" NOT NULL,
    challenge text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    goal text COLLATE pg_catalog."default" NOT NULL,
    "assessorId" uuid NOT NULL,
    "mentorNote" text COLLATE pg_catalog."default",
    "assessorNote" text COLLATE pg_catalog."default",
    accepted boolean,
    CONSTRAINT challenge_proposals_pkey PRIMARY KEY ("proposalId")
);

DROP TABLE IF EXISTS public.challenge_submission;

CREATE TABLE IF NOT EXISTS public.challenge_submission
(
    "submissionId" uuid NOT NULL,
    "studentId" uuid NOT NULL,
    award text COLLATE pg_catalog."default" NOT NULL,
    challenge text COLLATE pg_catalog."default" NOT NULL,
    "assessorId" uuid,
    "studentReflection" text COLLATE pg_catalog."default" NOT NULL,
    "mentorReflection" text COLLATE pg_catalog."default",
    "assessorReflection" text COLLATE pg_catalog."default",
    accepted boolean,
    CONSTRAINT challenge_submission_pkey PRIMARY KEY ("submissionId")
);

DROP TABLE IF EXISTS public.logs;

CREATE TABLE IF NOT EXISTS public.logs
(
    "logId" uuid NOT NULL,
    "studentId" uuid NOT NULL,
    award text COLLATE pg_catalog."default" NOT NULL,
    challenge text COLLATE pg_catalog."default" NOT NULL,
    evidence bytea NOT NULL,
    date timestamp with time zone NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    "mentorId" uuid NOT NULL,
    approved boolean,
    CONSTRAINT logs_pkey PRIMARY KEY ("logId")
);

DROP TABLE IF EXISTS public.student_challenge;

CREATE TABLE IF NOT EXISTS public.student_challenge
(
    "mentorId" uuid NOT NULL,
    "studentId" uuid NOT NULL,
    award text COLLATE pg_catalog."default" NOT NULL,
    challenge text COLLATE pg_catalog."default" NOT NULL,
    "approvedProposalId" uuid,
    "approvedSubmissionId" uuid,
    CONSTRAINT student_challenge_pkey PRIMARY KEY ("studentId", award, challenge),
    CONSTRAINT "student_challenge_approvedProposalId_key" UNIQUE ("approvedProposalId"),
    CONSTRAINT "student_challenge_approvedSubmissionId_key" UNIQUE ("approvedSubmissionId")
);

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    "userId" uuid NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY ("userId")
);

ALTER TABLE IF EXISTS public.challenge_proposals
    ADD CONSTRAINT "challenge_proposals_assessorId_fkey" FOREIGN KEY ("assessorId")
    REFERENCES public.assessors ("assesorId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.challenge_proposals
    ADD CONSTRAINT "challenge_proposals_studentId_award_challenge_fkey" FOREIGN KEY ("studentId", award, challenge)
    REFERENCES public.student_challenge ("studentId", award, challenge) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.challenge_submission
    ADD CONSTRAINT "challenge_submission_assessorId_fkey" FOREIGN KEY ("assessorId")
    REFERENCES public.assessors ("assesorId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.challenge_submission
    ADD CONSTRAINT "challenge_submission_studentId_award_challenge_fkey" FOREIGN KEY ("studentId", award, challenge)
    REFERENCES public.student_challenge ("studentId", award, challenge) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.logs
    ADD CONSTRAINT "logs_studentId_award_challenge_fkey" FOREIGN KEY ("studentId", award, challenge)
    REFERENCES public.student_challenge ("studentId", award, challenge) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_challenge
    ADD CONSTRAINT "student_challenge_approvedProposalId_fkey" FOREIGN KEY ("approvedProposalId")
    REFERENCES public.challenge_proposals ("proposalId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "student_challenge_approvedProposalId_key"
    ON public.student_challenge("approvedProposalId");


ALTER TABLE IF EXISTS public.student_challenge
    ADD CONSTRAINT "student_challenge_approvedSubmissionId_fkey" FOREIGN KEY ("approvedSubmissionId")
    REFERENCES public.challenge_submission ("submissionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "student_challenge_approvedSubmissionId_key"
    ON public.student_challenge("approvedSubmissionId");


ALTER TABLE IF EXISTS public.student_challenge
    ADD CONSTRAINT student_challenge_award_fkey FOREIGN KEY (award)
    REFERENCES public.awards (award) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_challenge
    ADD CONSTRAINT student_challenge_challenge_fkey FOREIGN KEY (challenge)
    REFERENCES public.challenge (challenge) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_challenge
    ADD CONSTRAINT "student_challenge_mentorId_fkey" FOREIGN KEY ("mentorId")
    REFERENCES public.users ("userId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student_challenge
    ADD CONSTRAINT "student_challenge_studentId_fkey" FOREIGN KEY ("studentId")
    REFERENCES public.users ("userId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;