/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as MentorRouteRouteImport } from './routes/mentor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentAwardRouteRouteImport } from './routes/student/$award/route'
import { Route as MentorStudentIdRouteRouteImport } from './routes/mentor/$studentId/route'
import { Route as StudentAwardIndexRouteImport } from './routes/student/$award/index'
import { Route as StudentAwardChallengeRouteImport } from './routes/student/$award/$challenge'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MentorStudentIdAwardRouteRouteImport } from './routes/mentor/$studentId/$award/route'
import { Route as MentorStudentIdAwardChallengeRouteImport } from './routes/mentor/$studentId/$award/$challenge'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRouteRoute = MentorRouteRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAwardRouteRoute = StudentAwardRouteRouteImport.update({
  id: '/$award',
  path: '/$award',
  getParentRoute: () => StudentRouteRoute,
} as any)
const MentorStudentIdRouteRoute = MentorStudentIdRouteRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => MentorRouteRoute,
} as any)
const StudentAwardIndexRoute = StudentAwardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentAwardRouteRoute,
} as any)
const StudentAwardChallengeRoute = StudentAwardChallengeRouteImport.update({
  id: '/$challenge',
  path: '/$challenge',
  getParentRoute: () => StudentAwardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorStudentIdAwardRouteRoute =
  MentorStudentIdAwardRouteRouteImport.update({
    id: '/$award',
    path: '/$award',
    getParentRoute: () => MentorStudentIdRouteRoute,
  } as any)
const MentorStudentIdAwardChallengeRoute =
  MentorStudentIdAwardChallengeRouteImport.update({
    id: '/$challenge',
    path: '/$challenge',
    getParentRoute: () => MentorStudentIdAwardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mentor': typeof MentorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mentor/$studentId': typeof MentorStudentIdRouteRouteWithChildren
  '/student/$award': typeof StudentAwardRouteRouteWithChildren
  '/mentor/$studentId/$award': typeof MentorStudentIdAwardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/student/$award/$challenge': typeof StudentAwardChallengeRoute
  '/student/$award/': typeof StudentAwardIndexRoute
  '/mentor/$studentId/$award/$challenge': typeof MentorStudentIdAwardChallengeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentor': typeof MentorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mentor/$studentId': typeof MentorStudentIdRouteRouteWithChildren
  '/mentor/$studentId/$award': typeof MentorStudentIdAwardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/student/$award/$challenge': typeof StudentAwardChallengeRoute
  '/student/$award': typeof StudentAwardIndexRoute
  '/mentor/$studentId/$award/$challenge': typeof MentorStudentIdAwardChallengeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mentor': typeof MentorRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mentor/$studentId': typeof MentorStudentIdRouteRouteWithChildren
  '/student/$award': typeof StudentAwardRouteRouteWithChildren
  '/mentor/$studentId/$award': typeof MentorStudentIdAwardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/student/$award/$challenge': typeof StudentAwardChallengeRoute
  '/student/$award/': typeof StudentAwardIndexRoute
  '/mentor/$studentId/$award/$challenge': typeof MentorStudentIdAwardChallengeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mentor'
    | '/student'
    | '/login'
    | '/signup'
    | '/mentor/$studentId'
    | '/student/$award'
    | '/mentor/$studentId/$award'
    | '/api/auth/$'
    | '/student/$award/$challenge'
    | '/student/$award/'
    | '/mentor/$studentId/$award/$challenge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mentor'
    | '/student'
    | '/login'
    | '/signup'
    | '/mentor/$studentId'
    | '/mentor/$studentId/$award'
    | '/api/auth/$'
    | '/student/$award/$challenge'
    | '/student/$award'
    | '/mentor/$studentId/$award/$challenge'
  id:
    | '__root__'
    | '/'
    | '/mentor'
    | '/student'
    | '/login'
    | '/signup'
    | '/mentor/$studentId'
    | '/student/$award'
    | '/mentor/$studentId/$award'
    | '/api/auth/$'
    | '/student/$award/$challenge'
    | '/student/$award/'
    | '/mentor/$studentId/$award/$challenge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MentorRouteRoute: typeof MentorRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$award': {
      id: '/student/$award'
      path: '/$award'
      fullPath: '/student/$award'
      preLoaderRoute: typeof StudentAwardRouteRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/mentor/$studentId': {
      id: '/mentor/$studentId'
      path: '/$studentId'
      fullPath: '/mentor/$studentId'
      preLoaderRoute: typeof MentorStudentIdRouteRouteImport
      parentRoute: typeof MentorRouteRoute
    }
    '/student/$award/': {
      id: '/student/$award/'
      path: '/'
      fullPath: '/student/$award/'
      preLoaderRoute: typeof StudentAwardIndexRouteImport
      parentRoute: typeof StudentAwardRouteRoute
    }
    '/student/$award/$challenge': {
      id: '/student/$award/$challenge'
      path: '/$challenge'
      fullPath: '/student/$award/$challenge'
      preLoaderRoute: typeof StudentAwardChallengeRouteImport
      parentRoute: typeof StudentAwardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/$studentId/$award': {
      id: '/mentor/$studentId/$award'
      path: '/$award'
      fullPath: '/mentor/$studentId/$award'
      preLoaderRoute: typeof MentorStudentIdAwardRouteRouteImport
      parentRoute: typeof MentorStudentIdRouteRoute
    }
    '/mentor/$studentId/$award/$challenge': {
      id: '/mentor/$studentId/$award/$challenge'
      path: '/$challenge'
      fullPath: '/mentor/$studentId/$award/$challenge'
      preLoaderRoute: typeof MentorStudentIdAwardChallengeRouteImport
      parentRoute: typeof MentorStudentIdAwardRouteRoute
    }
  }
}

interface MentorStudentIdAwardRouteRouteChildren {
  MentorStudentIdAwardChallengeRoute: typeof MentorStudentIdAwardChallengeRoute
}

const MentorStudentIdAwardRouteRouteChildren: MentorStudentIdAwardRouteRouteChildren =
  {
    MentorStudentIdAwardChallengeRoute: MentorStudentIdAwardChallengeRoute,
  }

const MentorStudentIdAwardRouteRouteWithChildren =
  MentorStudentIdAwardRouteRoute._addFileChildren(
    MentorStudentIdAwardRouteRouteChildren,
  )

interface MentorStudentIdRouteRouteChildren {
  MentorStudentIdAwardRouteRoute: typeof MentorStudentIdAwardRouteRouteWithChildren
}

const MentorStudentIdRouteRouteChildren: MentorStudentIdRouteRouteChildren = {
  MentorStudentIdAwardRouteRoute: MentorStudentIdAwardRouteRouteWithChildren,
}

const MentorStudentIdRouteRouteWithChildren =
  MentorStudentIdRouteRoute._addFileChildren(MentorStudentIdRouteRouteChildren)

interface MentorRouteRouteChildren {
  MentorStudentIdRouteRoute: typeof MentorStudentIdRouteRouteWithChildren
}

const MentorRouteRouteChildren: MentorRouteRouteChildren = {
  MentorStudentIdRouteRoute: MentorStudentIdRouteRouteWithChildren,
}

const MentorRouteRouteWithChildren = MentorRouteRoute._addFileChildren(
  MentorRouteRouteChildren,
)

interface StudentAwardRouteRouteChildren {
  StudentAwardChallengeRoute: typeof StudentAwardChallengeRoute
  StudentAwardIndexRoute: typeof StudentAwardIndexRoute
}

const StudentAwardRouteRouteChildren: StudentAwardRouteRouteChildren = {
  StudentAwardChallengeRoute: StudentAwardChallengeRoute,
  StudentAwardIndexRoute: StudentAwardIndexRoute,
}

const StudentAwardRouteRouteWithChildren =
  StudentAwardRouteRoute._addFileChildren(StudentAwardRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentAwardRouteRoute: typeof StudentAwardRouteRouteWithChildren
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAwardRouteRoute: StudentAwardRouteRouteWithChildren,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MentorRouteRoute: MentorRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
