/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentTierRouteImport } from './routes/student/$tier'
import { Route as StudentTierChallengeRouteImport } from './routes/student/$tier.$challenge'

const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTierRoute = StudentTierRouteImport.update({
  id: '/$tier',
  path: '/$tier',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentTierChallengeRoute = StudentTierChallengeRouteImport.update({
  id: '/$challenge',
  path: '/$challenge',
  getParentRoute: () => StudentTierRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/student/$tier': typeof StudentTierRouteWithChildren
  '/student/$tier/$challenge': typeof StudentTierChallengeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/student/$tier': typeof StudentTierRouteWithChildren
  '/student/$tier/$challenge': typeof StudentTierChallengeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/student/$tier': typeof StudentTierRouteWithChildren
  '/student/$tier/$challenge': typeof StudentTierChallengeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/student' | '/student/$tier' | '/student/$tier/$challenge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/student' | '/student/$tier' | '/student/$tier/$challenge'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/student/$tier'
    | '/student/$tier/$challenge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$tier': {
      id: '/student/$tier'
      path: '/$tier'
      fullPath: '/student/$tier'
      preLoaderRoute: typeof StudentTierRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/$tier/$challenge': {
      id: '/student/$tier/$challenge'
      path: '/$challenge'
      fullPath: '/student/$tier/$challenge'
      preLoaderRoute: typeof StudentTierChallengeRouteImport
      parentRoute: typeof StudentTierRoute
    }
  }
}

interface StudentTierRouteChildren {
  StudentTierChallengeRoute: typeof StudentTierChallengeRoute
}

const StudentTierRouteChildren: StudentTierRouteChildren = {
  StudentTierChallengeRoute: StudentTierChallengeRoute,
}

const StudentTierRouteWithChildren = StudentTierRoute._addFileChildren(
  StudentTierRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentTierRoute: typeof StudentTierRouteWithChildren
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentTierRoute: StudentTierRouteWithChildren,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRouteRoute: StudentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
