/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentAwardRouteImport } from './routes/student/$award'
import { Route as StudentAwardChallengeRouteImport } from './routes/student/$award.$challenge'

const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAwardRoute = StudentAwardRouteImport.update({
  id: '/$award',
  path: '/$award',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAwardChallengeRoute = StudentAwardChallengeRouteImport.update({
  id: '/$challenge',
  path: '/$challenge',
  getParentRoute: () => StudentAwardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/student/$award': typeof StudentAwardRouteWithChildren
  '/student/$award/$challenge': typeof StudentAwardChallengeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/student/$award': typeof StudentAwardRouteWithChildren
  '/student/$award/$challenge': typeof StudentAwardChallengeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/student/$award': typeof StudentAwardRouteWithChildren
  '/student/$award/$challenge': typeof StudentAwardChallengeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/student' | '/student/$award' | '/student/$award/$challenge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/student' | '/student/$award' | '/student/$award/$challenge'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/student/$award'
    | '/student/$award/$challenge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$award': {
      id: '/student/$award'
      path: '/$award'
      fullPath: '/student/$award'
      preLoaderRoute: typeof StudentAwardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/$award/$challenge': {
      id: '/student/$award/$challenge'
      path: '/$challenge'
      fullPath: '/student/$award/$challenge'
      preLoaderRoute: typeof StudentAwardChallengeRouteImport
      parentRoute: typeof StudentAwardRoute
    }
  }
}

interface StudentAwardRouteChildren {
  StudentAwardChallengeRoute: typeof StudentAwardChallengeRoute
}

const StudentAwardRouteChildren: StudentAwardRouteChildren = {
  StudentAwardChallengeRoute: StudentAwardChallengeRoute,
}

const StudentAwardRouteWithChildren = StudentAwardRoute._addFileChildren(
  StudentAwardRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentAwardRoute: typeof StudentAwardRouteWithChildren
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAwardRoute: StudentAwardRouteWithChildren,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRouteRoute: StudentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
